window.__ModuleLoader__.load({
	id: "@eli/eli-mode",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
		var React = require("react");

		// ═══════════════════════════════════════════════════════════════════
		// eli-mode 客户端：管理卡片（插件-插件配置 → 一级卡）+ 可选界面润色。
		// 润色（polish）默认关闭，由设置项 eli-mode.polish 控制，卡片里勾选，
		// 免刷新实时开关。自包含实现，服务经 ctx.get 惰性获取，失败只告警。
		// 文案走 locale 词典（NS = 'eli-mode'），随主界面语言切换。
		// ═══════════════════════════════════════════════════════════════════

		const NS = 'eli-mode';
		const LOCALES = {
			zh: {
				'card.title': 'Eli Mode',
				'card.desc': '人格 prompt、知识库注入 prompt 与界面润色',
				'card.loading': 'eli-mode 设置加载中…',
				'card.notExposed': '当前 DSH 版本未向设置页暴露 eli-mode 命名空间，表单不可用；可直接编辑 ~/.dsh/settings.yaml。',
				'kb.open': '打开知识库（新标签页）',
				'kb.openHint': '知识库页面由 web-routes 提供（/eli-kb），支持浏览 / 编辑 / 搜索条目。',
				'persona.label': '人格 prompt',
				'persona.placeholder': '在此输入人格 prompt…',
				'persona.hint': 'Role / 工作目录 / 日期由系统自动生成，无需包含；留空保存 = 恢复内置默认。',
				'kbPrompt.label': '知识库注入 prompt',
				'kbPrompt.placeholder': '知识库目录如下，用 kb_read / kb_search 按需取用：\n\n{{tree}}',
				'kbPrompt.hint': '{{tree}} 会被知识库目录清单替换；留空保存 = 不注入。',
				'kbIndex.label': '注入知识库目录',
				'kbIndex.on': '开（默认，会话注入知识库目录清单）',
				'kbIndex.off': '关',
				'polish.label': '界面润色（polish）',
				'polish.off': '关（默认，不改动界面）',
				'polish.on': '开（立绘、知识库标签页、token 统计、工具调用折叠）',
				'polish.hint': '免刷新生效：开 = 应用界面润色；关 = 恢复默认 UI。',
				'art.label': '更换立绘',
				'art.main': '主界面立绘',
				'art.wiki': 'wiki 界面立绘',
				'art.hint': '推荐竖版 PNG / WebP：主界面约 520×780、wiki 界面约 300×450。上传后立即生效。',
				'art.uploading': '上传中…',
				'art.mainDone': '主界面立绘已更新 ✓',
				'art.wikiDone': 'wiki 界面立绘已更新 ✓',
				'art.fail': '失败：',
				'art.netFail': '失败：网络错误',
				'save.saving': '保存中…',
				'save.save': '保存',
				'save.discard': '放弃',
				'save.failed': '保存未生效，请检查后重试。',
				'save.timeout': '写入超时（10 秒），请检查连接后重试',
				'stats.cache': '缓存 {pct}%',
				'stats.total': '总 {n} tok',
				'stats.balance': '余额 {cur}{amt}',
				'wikiTab.label': '知识库',
			},
			en: {
				'card.title': 'Eli Mode',
				'card.desc': 'Persona prompt, KB injection prompt and UI polish',
				'card.loading': 'Loading eli-mode settings…',
				'card.notExposed': 'The current DSH version does not expose the eli-mode namespace to the settings page. Edit ~/.dsh/settings.yaml directly, or whitelist it in WEB_SETTINGS_NAMESPACES.',
				'kb.open': 'Open knowledge base (new tab)',
				'kb.openHint': 'The KB page is served by web-routes at /eli-kb — browse, edit and search entries.',
				'persona.label': 'Persona prompt',
				'persona.placeholder': 'Enter the persona prompt…',
				'persona.hint': 'Role / cwd / date are generated by the system; leave empty and save to restore the built-in default.',
				'kbPrompt.label': 'KB injection prompt',
				'kbPrompt.placeholder': 'Knowledge base index below; use kb_read / kb_search on demand:\n\n{{tree}}',
				'kbPrompt.hint': '{{tree}} is replaced by the directory list; empty = no injection.',
				'kbIndex.label': 'Inject KB index',
				'kbIndex.on': 'On (default; inject the index into the session prompt)',
				'kbIndex.off': 'Off',
				'polish.label': 'UI polish',
				'polish.off': 'Off (default; stock UI untouched)',
				'polish.on': 'On (character art, KB tab, token stats, tool-call collapsing)',
				'polish.hint': 'Takes effect immediately: on = apply UI polish; off = restore default UI.',
				'art.label': 'Replace character art',
				'art.main': 'Main UI art',
				'art.wiki': 'Wiki UI art',
				'art.hint': 'Vertical PNG / WebP recommended: main UI ~520×780, wiki ~300×450. Applies immediately.',
				'art.uploading': 'Uploading…',
				'art.mainDone': 'Main UI art updated ✓',
				'art.wikiDone': 'Wiki UI art updated ✓',
				'art.fail': 'Failed: ',
				'art.netFail': 'Failed: network error',
				'save.saving': 'Saving…',
				'save.save': 'Save',
				'save.discard': 'Discard',
				'save.failed': 'Save did not land; check and retry.',
				'save.timeout': 'Write timed out (10s); check the connection and retry',
				'stats.cache': 'cache {pct}%',
				'stats.total': '{n} tok',
				'stats.balance': 'balance {cur}{amt}',
				'wikiTab.label': 'Knowledge base',
			},
		};
		function makeT(dict) {
			return (key) => (dict && dict[key]) || LOCALES.zh[key] || key;
		}

		function makeMiniStore(initial) {
			let snapshot = initial;
			const listeners = new Set();
			return {
				getSnapshot: () => snapshot,
				subscribe: (fn) => { listeners.add(fn); return () => listeners.delete(fn); },
				set: (s) => { snapshot = s; listeners.forEach((fn) => fn()); }
			};
		}

		// ── 设置字段（与 host 侧 schema 保持一致）──────────────────────────
		const ELI_MODE_FIELDS = {
			personaPrompt: {
				format: (v) => typeof v === 'string' ? v : '',
				parse: (text) => text.trim() === '' ? { kind: 'clear' } : { kind: 'set', value: text }
			},
			kbIndexPrompt: {
				format: (v) => typeof v === 'string' ? v : '',
				parse: (text) => text.trim() === '' ? { kind: 'clear' } : { kind: 'set', value: text }
			},
			kbIndex: {
				format: (v) => v === false ? false : true,
				parse: (v) => v === true || v === false ? { kind: 'set', value: v } : undefined
			},
			polish: {
				format: (v) => v === false ? false : true,
				parse: (v) => v === true || v === false ? { kind: 'set', value: v } : undefined
			}
		};
		class EliModeCardController {
			constructor(scope) {
				this.scope = scope;
				this.draft = new Map();
				this.saving = false;
				this.failed = false;
				this.failText = '';
				this.failDetail = '';
				this.store = makeMiniStore(null);
				scope.subscribe(() => this.publish());
				this.publish();
			}
			snapshot() {
				const snap = this.scope.getSnapshot();
				const plan = this.plan();
				const state = {
					available: snap.status !== 'loading',
					exposed: snap.status === 'ready',
					writable: !!snap.writable,
					dirty: plan.length > 0,
					invalid: plan.some((w) => w.run === undefined),
					saving: this.saving,
					failed: this.failed,
					failText: this.failText || '',
					failDetail: this.failDetail || ''
				};
				state.personaPrompt = this.field('personaPrompt');
				state.kbIndexPrompt = this.field('kbIndexPrompt');
				state.kbIndex = this.field('kbIndex');
				state.polish = this.field('polish');
				return state;
			}
			field(name) {
				const spec = ELI_MODE_FIELDS[name];
				const staged = this.draft.get(name);
				if (staged === undefined) {
					return { text: spec.format(this.value(name)), overridden: this.stored(name), invalid: false };
				}
				const write = staged.clear ? { kind: 'clear' } : spec.parse(staged.text);
				return { text: staged.text, overridden: write !== undefined && write.kind === 'set', invalid: write === undefined };
			}
			plan() {
				const plan = [];
				this.draft.forEach((staged, name) => {
					const spec = ELI_MODE_FIELDS[name];
					if (staged.clear) {
						if (this.stored(name)) plan.push({ name, run: () => this.clear(name) });
						return;
					}
					if (staged.text === spec.format(this.value(name))) return;
					const write = spec.parse(staged.text);
					if (write === undefined) plan.push({ name, run: undefined });
					else if (write.kind === 'clear') plan.push({ name, run: () => this.clear(name) });
					else plan.push({ name, run: () => this.writeField(name, write.value) });
				});
				return plan;
			}
			async save() {
				const plan = this.plan();
				if (plan.length === 0 || this.saving || plan.some((w) => w.run === undefined)) return;
				this.saving = true;
				this.failed = false;
				this.failText = '';
				this.failDetail = '';
				this.publish();
				let landed = true;
				let failKey = '';
				let failDetail = '';
				try {
					for (const item of plan) {
						try {
							// 每次写入带 10s 超时竞速：scope.set 万一永不归还，UI 也不会卡死在「保存中」
							const outcome = await Promise.race([
								Promise.resolve().then(item.run),
								new Promise((resolve) => setTimeout(() => resolve('__timeout__'), 10000))
							]);
							if (outcome === '__timeout__') { landed = false; failKey = 'save.timeout'; break; }
							landed = outcome && landed;
						} catch (err) {
							landed = false;
							failKey = 'save.failed';
							failDetail = err instanceof Error ? err.message : String(err);
							break;
						}
					}
				} finally {
					if (landed) this.draft.clear();
					this.saving = false;
					this.failed = !landed;
					this.failText = failKey;
					this.failDetail = failDetail;
					if (!landed && failKey !== '' && typeof console !== 'undefined') console.error('[eli-mode] settings save failed:', failDetail || failKey);
					this.publish();
				}
			}
			async clear(name) { await this.scope.unset(name); return !this.stored(name); }
			// 注意：方法名不能叫 store()——构造器把 this.store 赋成了快照 store 对象，同名方法会被覆盖
			async writeField(name, value) { await this.scope.set(name, value); return this.user()[name] === value; }
			value(name) {
				const v = this.scope.getSnapshot().value;
				return v && typeof v === 'object' ? v[name] : undefined;
			}
			user() {
				const u = this.scope.getSnapshot().user;
				return u && typeof u === 'object' ? u : {};
			}
			stored(name) { return Object.prototype.hasOwnProperty.call(this.user(), name); }
			publish() { this.store.set(this.snapshot()); }
			inject() {
				return {
					hooks: { eliModeCard: this.store },
					edit: (name, text) => { this.draft.set(name, { text, clear: false }); this.failed = false; this.publish(); },
					resetField: (name) => {
						this.draft.set(name, { text: ELI_MODE_FIELDS[name].format(this.value(name)), clear: true });
						this.failed = false;
						this.publish();
					},
					save: () => { void this.save(); },
					discard: () => { if (this.draft.size === 0 && !this.failed) return; this.draft.clear(); this.failed = false; this.publish(); }
				};
			}
		}

		// ── 卡片外观 ────────────────────────────────────────────────────────
		const eliModeShellStyle = { borderRadius: '12px', border: '1px solid rgba(127,127,127,0.18)', listStyle: 'none', overflow: 'hidden', display: 'flex', flexDirection: 'column' };
		const eliModeHeaderStyle = { appearance: 'none', width: '100%', color: 'inherit', font: 'inherit', textAlign: 'left', cursor: 'pointer', background: 'transparent', border: '0', borderRadius: '12px', alignItems: 'center', gap: '12px', padding: '14px 16px', display: 'flex' };
		const eliModeHeadTextStyle = { flexDirection: 'column', flex: 1, gap: '4px', minWidth: '0', display: 'flex' };
		const eliModeNameStyle = { fontSize: '15px', fontWeight: 600, lineHeight: '1.4', color: 'inherit' };
		const eliModeDescStyle = { fontSize: '13px', lineHeight: '1.5', opacity: 0.65 };
		const eliModeBodyStyle = { borderTop: '1px solid rgba(127,127,127,0.18)', margin: '0 16px', padding: '12px 0 8px', display: 'flex', flexDirection: 'column', gap: '10px' };
		function eliModeChevron(open) {
			return React.createElement('svg', { width: '14', height: '14', viewBox: '0 0 14 14', fill: 'none', xmlns: 'http://www.w3.org/2000/svg', style: { flex: 'none', color: 'inherit', opacity: 0.65, transition: 'transform .16s', transform: open ? 'rotate(180deg)' : 'none' } },
				React.createElement('path', { d: 'M11.8486 5.5L11.4238 5.92383L8.69727 8.65137C8.44157 8.90706 8.21562 9.13382 8.01172 9.29785C7.79912 9.46883 7.55595 9.61756 7.25 9.66602C7.08435 9.69222 6.91565 9.69222 6.75 9.66602C6.44405 9.61756 6.20088 9.46883 5.98828 9.29785C5.78438 9.13382 5.55843 8.90706 5.30273 8.65137L2.57617 5.92383L2.15137 5.5L3 4.65137L3.42383 5.07617L6.15137 7.80273C6.42595 8.07732 6.59876 8.24849 6.74023 8.3623C6.87291 8.46904 6.92272 8.47813 6.9375 8.48047C6.97895 8.48703 7.02105 8.48703 7.0625 8.48047C7.07728 8.47813 7.12709 8.46904 7.25977 8.3623C7.40124 8.24849 7.57405 8.07732 7.84863 7.80273L10.5762 5.07617L11 4.65137L11.8486 5.5Z', fill: 'currentColor' }));
		}
		function eliModeShell(t, message) {
			return React.createElement('li', { style: eliModeShellStyle },
				React.createElement('div', { style: Object.assign({}, eliModeHeaderStyle, { cursor: 'default' }) },
					React.createElement('span', { style: eliModeHeadTextStyle },
						React.createElement('span', { style: eliModeNameStyle }, t('card.title')),
						React.createElement('span', { style: eliModeDescStyle }, message))));
		}
		function EliModeCard(props) {
			const state = typeof props.useEliModeCard === 'function' ? props.useEliModeCard((s) => s) : null;
			const t = typeof props.t === 'function' ? props.t : makeT(LOCALES.zh);
			const [open, setOpen] = React.useState(false);
			const [artStatus, setArtStatus] = React.useState('');
			if (state === null) return null;
			if (!state.available) return eliModeShell(t, t('card.loading'));
			if (!state.exposed) return eliModeShell(t, t('card.notExposed'));
			const disabled = !state.writable || state.saving;
			const uploadArt = (side) => {
				const input = document.createElement('input');
				input.type = 'file';
				input.accept = 'image/*';
				input.onchange = () => {
					const file = input.files && input.files[0];
					if (!file) return;
					const reader = new FileReader();
					reader.onload = () => {
						const data = String(reader.result).split(',')[1] || '';
						setArtStatus(t('art.uploading'));
						fetch('/eli-kb/api/art', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ side, data }) })
							.then((r) => r.json())
							.then((d) => {
								if (d && d.ok) {
									setArtStatus(side === 'left' ? t('art.mainDone') : t('art.wikiDone'));
									if (side === 'left') refreshPolishCss();
								} else {
									setArtStatus(t('art.fail') + ((d && d.error) || 'unknown'));
								}
							})
							.catch(() => setArtStatus(t('art.netFail')));
					};
					reader.readAsDataURL(file);
				};
				input.click();
			};
			const rowStyle = { display: 'flex', flexDirection: 'column', gap: '6px' };
			const labelStyle = { fontSize: '12px', fontWeight: 600, lineHeight: '16px' };
			const hintStyle = { fontSize: '12px', lineHeight: '16px', opacity: 0.6 };
			const inputStyle = { width: '100%', minHeight: '32px', padding: '6px 10px', borderRadius: '8px', border: '1px solid rgba(127,127,127,0.35)', background: 'transparent', color: 'inherit', fontFamily: 'inherit', fontSize: '13px', boxSizing: 'border-box' };
			const btnStyle = { padding: '6px 14px', borderRadius: '8px', border: '1px solid rgba(127,127,127,0.35)', background: 'transparent', color: 'inherit', cursor: 'pointer', fontSize: '13px', textDecoration: 'none', display: 'inline-flex', alignItems: 'center' };
			const saveFail = state.failed ? (t(state.failText || 'save.failed') + (state.failDetail !== '' ? ' (' + state.failDetail + ')' : '')) : '';
			return React.createElement('li', { style: eliModeShellStyle },
				React.createElement('button', { type: 'button', style: eliModeHeaderStyle, 'aria-expanded': open, onClick: () => setOpen(!open) },
					React.createElement('span', { style: eliModeHeadTextStyle },
						React.createElement('span', { style: eliModeNameStyle }, t('card.title')),
						React.createElement('span', { style: eliModeDescStyle }, t('card.desc'))),
					eliModeChevron(open)),
				open ? React.createElement('div', { style: eliModeBodyStyle },
					React.createElement('div', { style: rowStyle },
						React.createElement('a', { href: '/eli-kb', target: '_blank', rel: 'noreferrer', style: btnStyle }, t('kb.open')),
						React.createElement('div', { style: hintStyle }, t('kb.openHint'))),
					React.createElement('div', { style: rowStyle },
						React.createElement('label', { style: labelStyle }, t('persona.label')),
						React.createElement('textarea', {
							rows: 7,
							style: Object.assign({}, inputStyle, { resize: 'vertical', fontFamily: 'ui-monospace, Consolas, monospace' }),
							value: state.personaPrompt.text,
							disabled,
							placeholder: t('persona.placeholder'),
							onChange: (e) => props.edit('personaPrompt', e.target.value)
						}),
						React.createElement('div', { style: hintStyle }, t('persona.hint'))),
					React.createElement('div', { style: rowStyle },
						React.createElement('label', { style: labelStyle }, t('kbPrompt.label')),
						React.createElement('textarea', {
							rows: 4,
							style: Object.assign({}, inputStyle, { resize: 'vertical', fontFamily: 'ui-monospace, Consolas, monospace' }),
							value: state.kbIndexPrompt.text,
							disabled,
							placeholder: t('kbPrompt.placeholder'),
							onChange: (e) => props.edit('kbIndexPrompt', e.target.value)
						}),
						React.createElement('div', { style: hintStyle }, t('kbPrompt.hint'))),
					React.createElement('div', { style: rowStyle },
						React.createElement('label', { style: labelStyle }, t('kbIndex.label')),
						React.createElement('select', {
							style: inputStyle,
							value: String(state.kbIndex.text),
							disabled,
							onChange: (e) => props.edit('kbIndex', e.target.value === 'true')
						},
							React.createElement('option', { value: 'true' }, t('kbIndex.on')),
							React.createElement('option', { value: 'false' }, t('kbIndex.off')))),
					React.createElement('div', { style: rowStyle },
						React.createElement('label', { style: labelStyle }, t('polish.label')),
						React.createElement('select', {
							style: inputStyle,
							value: String(state.polish.text),
							disabled,
							onChange: (e) => props.edit('polish', e.target.value === 'true')
						},
							React.createElement('option', { value: 'false' }, t('polish.off')),
							React.createElement('option', { value: 'true' }, t('polish.on'))),
						React.createElement('div', { style: hintStyle }, t('polish.hint'))),
					React.createElement('div', { style: rowStyle },
						React.createElement('label', { style: labelStyle }, t('art.label')),
						React.createElement('div', { style: { display: 'flex', gap: '8px' } },
							React.createElement('button', { type: 'button', style: btnStyle, onClick: () => uploadArt('left') }, t('art.main')),
							React.createElement('button', { type: 'button', style: btnStyle, onClick: () => uploadArt('right') }, t('art.wiki'))),
						React.createElement('div', { style: hintStyle }, t('art.hint')),
						artStatus !== '' ? React.createElement('div', { style: hintStyle }, artStatus) : null),
					React.createElement('div', { style: { display: 'flex', gap: '8px', marginTop: '4px' } },
						React.createElement('button', { type: 'button', style: btnStyle, disabled: disabled || !state.dirty || state.invalid, onClick: () => props.save() }, state.saving ? t('save.saving') : t('save.save')),
						React.createElement('button', { type: 'button', style: btnStyle, disabled: disabled || (!state.dirty && !state.failed), onClick: () => props.discard() }, t('save.discard'))),
					saveFail !== '' ? React.createElement('div', { style: Object.assign({}, hintStyle, { color: '#e05a5a' }) }, saveFail) : null) : null);
		}

		// ═══════════════════════════════════════════════════════════════════
		// 界面润色（polish）：默认关，由 eli-mode.polish 控制，免刷新开关
		// ═══════════════════════════════════════════════════════════════════

		const POLISH_CSS = `body::after { content: ''; position: fixed; right: 10px; bottom: 0; width: 520px; height: 780px; z-index: 99998; pointer-events: none; background: url('/eli-kb/art/left') no-repeat bottom right / contain; opacity: .88; filter: drop-shadow(0 0 24px rgba(96,112,176,.3)); }
			body[data-eli-wiki]::after { display: none; }
			body button, body [class*='card'], body [class*='item'] { transition: background .18s ease, border-color .18s ease, box-shadow .18s ease, transform .18s ease; }
			body button:hover:not(:disabled) { transform: translateY(-1px); }
			/* 工具调用链合并（eli-toolchain）：默认收起为一行摘要，点击展开 */
			.eli-toolchain-call { display: none; }
			.eli-toolchain-run[data-eli-open="true"] ~ .eli-toolchain-call { display: block; }
			.eli-toolchain-run { appearance: none; width: 100%; text-align: left; display: flex; align-items: center; gap: 8px; margin: 2px 0; padding: 10px 14px; border: 1px solid rgba(127,127,127,0.25); border-radius: 10px; background: transparent; color: inherit; font: inherit; font-size: 13px; cursor: pointer; }
			.eli-toolchain-run:hover { border-color: rgba(127,127,127,0.5); }
			.eli-toolchain-label { opacity: 0.85; }
			.eli-toolchain-chevron { margin-left: auto; opacity: 0.6; transition: transform .16s; }
			.eli-toolchain-run[data-eli-open="true"] .eli-toolchain-chevron { transform: rotate(180deg); }`;

		function applyPolishCss() {
			if (typeof document === 'undefined') return;
			const tagId = '@eli/eli-mode/polish.css';
			if (document.querySelector("style[data-plugin-css='" + tagId + "']") === null) {
				const tag = document.createElement('style');
				tag.dataset.plugin = '@eli/eli-mode';
				tag.dataset.pluginCss = tagId;
				tag.textContent = POLISH_CSS;
				document.head.appendChild(tag);
			}
		}
		function removePolishCss() {
			if (typeof document === 'undefined') return;
			const tag = document.querySelector("style[data-plugin-css='" + '@eli/eli-mode/polish.css' + "']");
			if (tag !== null) tag.remove();
		}
		/** 更换立绘后重挂 CSS（no-store 保证重新拉取新图）。 */
		function refreshPolishCss() {
			removePolishCss();
			applyPolishCss();
		}

		/** 工具调用链合并（Codex 式），返回 dispose 以在关闭 polish 时清理现场。 */
		function setupToolchainCollapse() {
			if (typeof document === 'undefined' || document.body === null) return { dispose: () => {} };
			const isCall = (el) => el !== null && el.nodeType === 1 && el.matches('[data-chat-flow-kind="tool-call"]');
			const makeSummary = (count) => {
				const s = document.createElement('button');
				s.type = 'button';
				s.className = 'eli-toolchain-run';
				s.dataset.eliOpen = 'false';
				s.dataset.count = String(count);
				s.setAttribute('aria-expanded', 'false');
				const label = document.createElement('span');
				label.className = 'eli-toolchain-label';
				label.textContent = '调用工具 ×' + count;
				const chevron = document.createElement('span');
				chevron.className = 'eli-toolchain-chevron';
				chevron.textContent = '▾';
				s.appendChild(label);
				s.appendChild(chevron);
				s.addEventListener('click', () => {
					const open = s.dataset.eliOpen === 'true';
					s.dataset.eliOpen = open ? 'false' : 'true';
					s.setAttribute('aria-expanded', String(!open));
				});
				return s;
			};
			const setCount = (s, count) => {
				s.dataset.count = String(count);
				const l = s.querySelector('.eli-toolchain-label');
				if (l !== null) l.textContent = '调用工具 ×' + count;
			};
			let timer = null;
			const scan = () => {
				timer = null;
				try {
					const rows = document.querySelectorAll('[data-chat-flow-kind="tool-call"]');
					const processed = new Set();
					rows.forEach((row) => {
						if (processed.has(row)) return;
						if (row.classList.contains('eli-toolchain-call')) { processed.add(row); return; }
						const run = [row];
						let cursor = row.nextElementSibling;
						while (isCall(cursor) && !cursor.classList.contains('eli-toolchain-call')) {
							run.push(cursor);
							cursor = cursor.nextElementSibling;
						}
						const prev = row.previousElementSibling;
						if (prev !== null && prev.classList.contains('eli-toolchain-call')) {
							let s = prev;
							while (s !== null && !s.classList.contains('eli-toolchain-run')) s = s.previousElementSibling;
							if (s !== null) {
								run.forEach((r) => { r.classList.add('eli-toolchain-call'); processed.add(r); });
								setCount(s, (parseInt(s.dataset.count || '0', 10) || 0) + run.length);
								return;
							}
						}
						if (run.length >= 2) {
							const summary = makeSummary(run.length);
							row.before(summary);
							run.forEach((r) => { r.classList.add('eli-toolchain-call'); processed.add(r); });
						} else {
							processed.add(row);
						}
					});
				} catch (err) {
					if (typeof console !== 'undefined') console.warn('[eli-mode] toolchain collapse failed:', err);
				}
			};
			const schedule = () => { if (timer === null) timer = setTimeout(scan, 120); };
			const observer = new MutationObserver(schedule);
			observer.observe(document.body, { childList: true, subtree: true });
			schedule();
			return {
				dispose: () => {
					observer.disconnect();
					if (timer !== null) clearTimeout(timer);
					document.querySelectorAll('.eli-toolchain-run').forEach((el) => el.remove());
					document.querySelectorAll('.eli-toolchain-call').forEach((el) => el.classList.remove('eli-toolchain-call'));
				}
			};
		}

		// ── apply ──────────────────────────────────────────────────────────
		function apply(ctx) {
			const slots = ctx !== null && ctx !== void 0 && typeof ctx.get === 'function' ? ctx.get('slots') : void 0;
			if (slots === void 0) return;
			const locale = ctx.get('locale');
			if (locale && typeof locale.register === 'function') {
				locale.register(NS, { zh: LOCALES.zh, en: LOCALES.en });
			}
			let polishOn = false;
			let toolchainHandle = null;
			let slotDisposers = [];
			const fmt = (n) => n >= 1e6 ? (n / 1e6).toFixed(1) + 'M' : n >= 1e3 ? (n / 1e3).toFixed(1) + 'K' : String(n || 0);
			const sym = { 'CNY': '¥', 'USD': '$' };
			const dockStats = (props) => {
				const t = typeof props.t === 'function' ? props.t : makeT(LOCALES.zh);
				const usage = typeof props.useProjection === 'function' ? props.useProjection('tokenUsage') : void 0;
				const billed = usage ? (usage.uncachedInputTokens || 0) + (usage.cacheReadTokens || 0) + (usage.cacheWriteTokens || 0) : 0;
				const output = usage ? (usage.outputTokens || 0) : 0;
				const cacheHit = billed === 0 ? null : Math.round((usage.cacheReadTokens || 0) / billed * 100);
				const [bal, setBal] = React.useState(null);
				React.useEffect(() => {
					let alive = true;
					fetch('/eli-kb/api/balance').then((r) => r.json()).then((d) => { if (alive && d && d.ok) setBal(d); }).catch(() => {});
					return () => { alive = false; };
				}, []);
				const bits = [];
				if (cacheHit !== null) bits.push(t('stats.cache').replace('{pct}', String(cacheHit)));
				if (billed + output > 0) bits.push(t('stats.total').replace('{n}', fmt(billed + output)));
				if (bal !== null && typeof bal.balance === 'number') bits.push(t('stats.balance').replace('{cur}', sym[bal.currency] || '').replace('{amt}', bal.balance.toFixed(2)));
				return React.createElement('div', { style: { fontSize: '11px', letterSpacing: '0.04em', color: 'var(--dsw-alias-label-tertiary, var(--dsw-alias-label-secondary))', padding: '2px 0 0' } }, bits.length > 0 ? bits.join('  ·  ') : '');
			};
			const wikiView = (props) => {
				const t = typeof props.t === 'function' ? props.t : makeT(LOCALES.zh);
				React.useEffect(() => {
					if (typeof document !== 'undefined' && document.body !== null) document.body.setAttribute('data-eli-wiki', '');
					return () => { if (typeof document !== 'undefined' && document.body !== null) document.body.removeAttribute('data-eli-wiki'); };
				}, []);
				return React.createElement('iframe', { src: '/eli-kb', title: t('wikiTab.label'), style: { width: '100%', height: '100%', minHeight: '60vh', border: 'none', display: 'block', background: 'transparent' } });
			};
			const syncPolish = (scope) => {
				const snap = scope.getSnapshot();
				const on = snap.status === 'ready' && snap.value !== null && typeof snap.value === 'object' && snap.value.polish === true;
				if (on === polishOn) return;
				polishOn = on;
				try {
					if (on) {
						applyPolishCss();
						toolchainHandle = setupToolchainCollapse();
						slotDisposers = [
							slots.inject('conversation.composer.dock', () => slots.register({ name: 'conversation.composer.dock', id: 'stats', order: 0, priority: -1, locale: NS }, dockStats)),
							slots.inject('conversation.view', () => slots.register({ name: 'conversation.view', id: 'wiki', order: 20, label: () => (typeof locale.t === 'function' ? locale.t('wikiTab.label') : '知识库'), locale: NS }, wikiView))
						];
					} else {
						removePolishCss();
						if (toolchainHandle !== null) { toolchainHandle.dispose(); toolchainHandle = null; }
						slotDisposers.forEach((d) => { try { d(); } catch (_e) { /* ignore */ } });
						slotDisposers = [];
					}
				} catch (err) {
					if (typeof console !== 'undefined') console.warn('[eli-mode] polish sync failed:', err);
				}
			};
			try {
				let attempts = 0;
				const mountCard = () => {
					try {
						const binder = ctx.get('webUiSettings') || ctx.get('settingsScope');
						if (binder && typeof binder.bind === 'function') {
							const scope = binder.bind({ namespace: 'eli-mode' });
							const controller = new EliModeCardController(scope);
							slots.inject('settings.plugin.item', () => slots.register({
								name: 'settings.plugin.item',
								id: 'eli-mode-settings',
								order: 110,
								locale: NS,
								inject: () => controller.inject()
							}, EliModeCard));
							scope.subscribe(() => syncPolish(scope));
							syncPolish(scope);
							return true;
						}
					} catch (mountErr) {
						if (typeof console !== 'undefined') console.warn('[eli-mode] card attempt failed:', mountErr);
					}
					if (attempts++ < 40) setTimeout(mountCard, 500);
					return false;
				};
				mountCard();
			} catch (err) {
				if (typeof console !== 'undefined') console.warn('[eli-mode] card mount failed:', err);
			}
		}
		exports.apply = apply;
		return module.exports;
	}
});
